Kredeum/kredeum

.favorites.json, lib/knfts.ts, svelte/kredeum-list-nfts.svelte, svelte/kredeum-metamask.svelte
Adapts urls to different explorers
=> ExplorersUrl

.favorites.json, svelte/kredeum-list-nfts.svelte
fix NFT panel closing while loading new NFTs after refresh or first loading
=> FixPanelClose

common/lib/kcollection-get.ts, common/lib/kconfig.ts, common/lib/kfetch.ts
Fix when tokenURI points to ipfs:// instead of http(s)://
=> Fix tokenURI as ipfs://

common/.eslintrc.js, common/lib/kcollection-get.ts, common/lib/kcollection-list.ts, common/lib/knft-mint.ts, common/lib/ktypes.ts, common/package.json, hardhat/.eslintrc.js, hardhat/hardhat.config.ts, rollup/.eslintrc.js, rollup/svelte/kredeum-create-collection.svelte, rollup/svelte/kredeum-create-nft.svelte, rollup/svelte/kredeum-list-collections.svelte, rollup/svelte/kredeum-list-nfts.svelte, rollup/svelte/kredeum-metamask.svelte
New Mint not compatible with old OpenNFTs collections : OpenNFTs V2 V1 and V0
Ok with last OpenNFTsV3
=> Fix Mint bug on old OpenNFTs version

common/lib/kconfig.ts, svelte/components/kredeum-get-nft.svelte, svelte/components/kredeum-list-collections.svelte, svelte/components/kredeum-list-nfts.svelte, svelte/helpers/metamaskLib.ts, svelte/helpers/urlHash.ts
Direct access to NFT via hashtag in url
```
// URL = https://beta.kredeum.com/#/mainnet/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/771769
// HASH = #/mainnet/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/771769
// HASH = #/chainName/collectionAddress/tokenID
```
=> nft routing

.vscode/settings.json, common/config/config.json, common/lib/knft-mint.ts, common/lib/knft-storage.ts, wordpress/package.json, wordpress/plugins/kredeum-nfts/admin/media-list/column.php, wordpress/pnpm-lock.yaml, wordpress/readme.txt_handlebars
* Fix Mint button in WordPress media library, when media not already archived on IPFS
=> fix mint without cid

common/config/config.json, common/lib/kcollection-get-metadata.ts, common/lib/ktypes.ts, svelte/components/Collection/Collection.svelte, svelte/components/Collection/CollectionCreate.svelte, svelte/components/Collection/CollectionList.svelte, svelte/components/Network/Network.svelte, svelte/components/Nft/Nft.svelte, svelte/components/Nft/NftMint.svelte, svelte/components/Nft/NftMintButton.svelte, svelte/components/Nft/NftTransfer.svelte, svelte/components/Nft/NftsList.svelte, svelte/package.json, svelte/stores/collection/collectionSubList.ts, svelte/tests/CollectionListSimple.svelte, svelte/tests/CollectionSimple.svelte, svelte/tests/NftDetail.svelte, svelte/tests/NftSimple.svelte, svelte/tests/NftsDerived/App.svelte, svelte/tests/NftsListSimple.svelte, svelte/tests/Test01.svelte
Fix Mint button not showing up 
Also fix svelte-check errors and hints
=> Fix mint button

common/lib/kcollection-get-metadata.ts
Fix minting on OpenNFTsV0 and OpenNFTsV1
fix #183
=> Fix minting V0 V1

.github/workflows/dapp-build.yml, common/config/networks.json, common/lib/kcollection-get-metadata.ts, common/lib/kcollection-list.ts, common/lib/kconfig.ts, common/lib/kfetch.ts, common/lib/knft-list.ts, common/lib/ktransfer.ts, common/lib/ktypes.ts, common/scripts/alchemy.http
=> Alchemy api

common/lib/knft-list.ts, common/scripts/alchemy.http, svelte/components/Global/Content.svelte, svelte/components/Media/MediaDisplay.svelte, svelte/components/Media/MediaDisplayAudio.svelte, svelte/components/Media/MediaDisplayVideo.svelte, svelte/components/Media/MediaPreview.svelte, svelte/components/Nft/Nft.svelte, svelte/components/Nft/NftGrid.svelte, svelte/components/Nft/NftLine.svelte, svelte/components/NftsList/NftsListGrid.svelte, svelte/components/NftsList/NftsListLines.svelte, svelte/stores/nft/nft.ts
Fix index bug with tokenID too long
=> Fix index bug with tokenID too long

common/lib/kcollection-get.ts, common/lib/knft-get.ts, svelte/components/Media/MediaDisplay.svelte, svelte/components/Nft/Nft.svelte, svelte/tests/NftSimple.svelte, svelte/tests/Test02.svelte
<Nft /> component alone lacks metadata...
=> Fix Nft component

common/lib/api-alchemy.ts, common/lib/api-covalent.ts, common/lib/api-thegraph.ts, common/lib/kcollection-list.ts, common/lib/kconfig.ts, common/lib/kfetch.ts, common/lib/knft-list.ts
Refacto apis in one single file per provider
=> Refacto api

common/lib/kcollection-clone.ts
Fix Bad Template error
fix #238
=> Fix Bad Template

svelte/components/Collection/CollectionCreate.svelte, svelte/components/Collection/CollectionList.svelte, svelte/components/Global/Content.svelte, svelte/components/Global/Create.svelte, svelte/components/Global/Home.svelte, svelte/components/Nft/NftMint.svelte, svelte/components/NftsList/NftsList.svelte, svelte/components/NftsList/NftsListRefresh.svelte, svelte/package.json
refresh collection after collection creation & on refresh button click
refresh collection after nft mint & refresh nft after one block after nft mint
=> Refresh nft & collection after mint

svelte/.eslintrc.js, svelte/.prettierrc, svelte/package.json
Fix svelte formatting
eslint reformat file already formatted pby prettier
=> Fix formatting

.vscode/settings.json, common/config/networks.json, common/lib/kcollection-list.ts, common/lib/knft-list.ts, svelte/components/Nft/NftGrid.svelte
Improve performance with better API choice
Alchemy API by default to get Contracts Info and NFTs list
=> Improve performance

wordpress/tsconfig.json
fix build error in wordpress , causing deploying to fleek failing
=> fix wordpress ts config

package.json, pnpm-lock.yaml
fix ts-node missing when building
=> fix ts-node missing

common/lib/kautomarket.ts, common/lib/kburn.ts, common/lib/kbuy.ts, common/lib/kcollection-get.ts, common/lib/kconfig.ts, common/lib/kfactory-get.ts, common/lib/knft-get-metadata.ts, common/lib/knft-get.ts, common/lib/knft-mint.ts, common/lib/ktransfer.ts, common/lib/ktypes.ts, common/lib/resolver/resolver-conv-nft-infos.ts, common/lib/resolver/resolver-get-nft.ts, gulp/scss/_class.scss, svelte/components/Collection/CollectionCreate.svelte, svelte/components/Nft/Nft.svelte, svelte/components/Nft/NftBurn.svelte, svelte/components/Nft/NftBuy.svelte, svelte/components/Nft/NftMint.svelte, svelte/components/Nft/NftSell.svelte, svelte/components/Nft/NftTransfer.svelte, svelte/stores/nft/nft.ts, svelte/stores/nft/nftSubList.ts
- add default mint price info in mint modal
- add Price display in Nft details
- add sell button ( Approve & setPrice )
- add buy button in Nft details if not owner
- add burn button on Nft detail page ( remove burned nft from store and local storage after burn )
- Disable Transfer button when not effective
TODO :
- Get Price and royalties infos when not owner to permit buy function working
- Refresh after transfer
- Refresh after setPrice
- display sell button only on OpenNFTsV4 template
- refresh owner and buttons after buy
- Burn Nft buyed (owner of nft, not owner of collection)
=> New automarket UI

.vscode/settings.json, common/lib/apis/api-moralis.ts, common/lib/collection/kcollection-clone.ts, common/lib/common/kconfig.ts, common/lib/common/ktypes.ts, common/lib/nft/kautomarket.ts, common/lib/nft/kburn.ts, common/lib/nft/kbuy.ts, common/lib/resolver/resolver-conv-nft-infos.ts, gulp/scss/_class.scss, svelte/components/Collection/CollectionCreate.svelte, svelte/components/Nft/Nft.svelte, svelte/components/Nft/NftBurn.svelte, svelte/components/Nft/NftBuy.svelte, svelte/components/Nft/NftMint.svelte, svelte/components/Nft/NftSell.svelte, svelte/components/Nft/NftSetRoyalties.svelte
MANDATORY FOR MERGING :
OPTIONAL FEATURES OR AFTER MERGING :
=> Automarket UI

gulp/scss/front-md.scss, svelte/components/Account/Account.svelte, svelte/components/Account/AccountConnect.svelte, svelte/components/Collection/CollectionList.svelte, svelte/components/Global/CopyRefItem.svelte, svelte/components/Network/NetworkList.svelte, svelte/components/Nft/Nft.svelte, svelte/components/Nft/NftGrid.svelte, svelte/components/Nft/NftMintButton.svelte
see issue 5 refacto nft ref&links #212
=> 5 refacto nft ref&links

common/config/config.json, svelte/components/Nft/NftMint.svelte
=> Merge integ

svelte/components/Nft/NftSell.svelte, svelte/components/Nft/NftSetPrice.svelte
See issue refacto view on opensea button #290 
=> lighter "view on OpenSea" button placed on bottom-left of SELL modal
=> refacto view on opensea button

common/lib/common/ktypes.ts, common/lib/nft/storage/knft-ipfs.ts, svelte/components/Collection/CollectionCreate.svelte, svelte/components/Collection/CollectionList.svelte, svelte/components/Global/Content.svelte, svelte/components/Global/IncomesPreview.svelte, svelte/components/Global/Navigation.svelte, svelte/components/Media/MediaPreview.svelte, svelte/components/Network/NetworkList.svelte, svelte/components/Nft/NftBuy.svelte, svelte/components/Nft/NftLine.svelte, svelte/components/Nft/NftMint.svelte, svelte/components/Nft/NftMintButton.svelte, svelte/components/Nft/NftProperties.svelte, svelte/components/Nft/NftSell.svelte, svelte/components/Nft/NftTransfer.svelte, svelte/tests/CollectionListSimple.svelte, svelte/tests/CollectionSetApproval.svelte, svelte/tests/NftCopy.svelte, svelte/tests/NftSetRoyalties.svelte, svelte/tests/NftTokenApprove.svelte, svelte/tests/NftWithdraw.svelte
Fix NftMintButton when minting in medias in wordpress (minting without properties)
=> fix NftMintButton mint without properties

common/lib/collection/collection-get.ts
Fix crash when minting on all OpenNFTsV3 collections with latest version
=> Mint Bug on OpenNFTsV3 collections 

svelte/components/Nfts/Nfts.svelte, svelte/main/app.ts, wordpress/plugins/kredeum-nfts/common/shortcode/shortcode.php, wordpress/plugins/kredeum-nfts/public/front/automarket.php
Alias kredeum_opensky with kredeum_automarket for retro compatibility
=> Get back kredeum_automarket shortcode

LICENCE
=> MIT LICENCE

pnpm-lock.yaml, wordpress/plugins/kredeum-nfts/admin/media-list/column.php, wordpress/plugins/kredeum-nfts/admin/settings/fields.php, wordpress/plugins/kredeum-nfts/admin/storage/query.php
wordpress dispatch STORAGE_CHOICE in column.php
The value of IPFS or SWARM was stored in upercases in data base.
In this PR it have been changed to lowercase.
there's also a fix of nftstorage key import from config.json
=> Wordpress dispatch Storage

common/lib/collection/collection-get.ts, common/lib/common/config.ts, common/lib/nft/nft-get-metadata.ts, common/lib/nft/nft.ts, gulp/scss/front.scss, pnpm-lock.yaml, svelte/components/Nft/NftBuy.svelte, svelte/components/Nft/NftIncomes.svelte, svelte/components/Nft/NftSetPrice.svelte
=> Fix price bugs on v1.1

gulp/scss/_class.scss, gulp/scss/front.scss
Fix white background display on grid cards
Refacto cards margin-bottom by using same class for dapp and OpenSky
=> fix background card display & margin bottom

gulp/scss/_class.scss, svelte/components/Nft/NftBuy.svelte
Fix not on sale button in Nft detail.
Add aria-disabled attribute for accessibility
=> Fix not on sale button

common/lib/common/config.ts, common/lib/nft/nft-mint.ts
Fix legacy evm , non Eip1559 compatible
i.e. transaction type 0 , not type 2
=> Fix legacy evm

common/config/networks.handlebars.json, common/deployments/telostestnet/OpenAutoMarket.json, common/deployments/telostestnet/OpenNFTsResolver.json
=> Telos testnet

common/config/config.handlebars.json, common/lib/common/beejs.ts, common/lib/nft/storage/storage.ts, common/lib/nft/storage/swarm.ts, wordpress/plugins/kredeum-nfts/admin/settings/storage-choice.js
- fix object.assign conflict in nested oject in "storage.ts" (still typescript error) 
- Fix empty fields overides on localstorage in Wordpress "storage-choice.js"
- Refacto swarm libs & beejs.ts & swarm contants
Tested with Swarm Gateway, local node (pined), opened port with Ngrok (pined)
=> fix storage choice
